# conda activate /home/etu-admin/Desktop/Flavia/internship/cyu_tut
# Gym docs: https://gymnasium.farama.org/environments/toy_text/frozen_lake/

import gymnasium as gym
import numpy as np
import math
import random
from train import Trainer
from agent import CustomRewardWrapper
from plot import plot_qvalue_snapshots, plot_replay_trajectories

UPDATE_MODES = ["std", "std_punish", "opposite", "relative", "relative_punish"]    
REPLAY_MODES = ["none", "prioritized_sweeping", "value_iteration", "backward", "dyna"]

# --------------- CONFIG ---------------
UPDATE_MODE     = UPDATE_MODES[0]
REPLAY_MODE     = REPLAY_MODES[1]

TRAINING_EPS    = 750
MAX_EPS_STEPS   = 100

REPLAY_STEPS    = 25

SHIFT_GOAL_EP   = TRAINING_EPS // 2
SHIFT_GOAL_POS  = (2, 8)

GRID_SIZE       = 10    

# --------------- OBSTACLES CONFIG ---------------
ADD_OBS_EP       = None #TRAINING_EPS // 3
OBSTACLES_COUNT  = 15

# --------------- PARAMS ---------------
EPSILON_START   = 1.0
EPSILON_MIN     = 0.05
DECAY_RATE      = math.exp(math.log(EPSILON_MIN / EPSILON_START) / (TRAINING_EPS / 2 * 0.8)) # epsilon decay factor
Q_INIT          = 0.0
GAMMA           = 0.99
ALPHA           = 0.3
ALPHA_V         = 0.3

# --------------- REPLAY PARAMS ---------------
BACKWARD_STEPS  = 10
DYNA_STEPS      = 15
PS_STEPS        = 15
THETA           = 0.0001

OUTDIR           = "./QLearning/visuals"
SHIFTDIR         = (f"_shift" if SHIFT_GOAL_EP is not None else "")
OBSDIR           = (f"_obstacle" if ADD_OBS_EP is not None else "")
    
def make_env(update_mode, goal_row=9, goal_col=9, obstacles_count=0, fixed_obstacles=None):
    
    # creating custom grid, all std frozen cells
    grid = [['F' for _ in range(GRID_SIZE)] for _ in range(GRID_SIZE)]
    
    # positioning start and goal
    grid[0][0] = 'S'
    grid[goal_row][goal_col] = 'G'
    
    # finding all available cells
    if fixed_obstacles is not None:
        obstacle_spots = fixed_obstacles
    else:
        available_spots = [(r, c) for r in range(GRID_SIZE) for c in range(GRID_SIZE) 
                        if grid[r][c] not in ['S', 'G']]

        # randomicaly selecting where to place obstacles
        actual_obstacles = min(obstacles_count, len(available_spots)) # min to place only one per cell
        obstacle_spots = random.sample(available_spots, actual_obstacles)
    
    # actually placing holes
    for r, c in obstacle_spots:
        if grid[r][c] not in ['S', 'G']:
            grid[r][c] = 'H'
        
    rows = ["".join(row) for row in grid]

    env_kwargs = {
        "is_slippery": False,
        "desc": rows
    }

    env = gym.make("FrozenLake-v1", max_episode_steps=MAX_EPS_STEPS, **env_kwargs)
    env = CustomRewardWrapper(env, update_mode)

    return env, env_kwargs, obstacle_spots

def make_agent(env, update_mode, replay_mode, initial_obstacles):

    current_obstacles = list(initial_obstacles) if initial_obstacles else []

    # creating function that generates env with shifted goal and/or obstacles
    # taking only first obj generated by make_env, which is the actual env
    def env_factory(row, col, obstacles_active):
        nonlocal current_obstacles

        # if wanting obstacles > 0
        if obstacles_active and OBSTACLES_COUNT > 0:
            # if obs not sotred generating them
            if not current_obstacles:
                env, _, new_obs = make_env(update_mode, goal_row=row, goal_col=col, obstacles_count=OBSTACLES_COUNT)
                current_obstacles.extend(new_obs)
                return env
            # if already stored using fixed positions
            else:
                env, _, _ = make_env(update_mode, goal_row=row, goal_col=col, fixed_obstacles=current_obstacles)
                return env
        else:
            # Niente ostacoli
            env, _, _ = make_env(update_mode, goal_row=row, goal_col=col, obstacles_count=0)
            return env
        
    return Trainer(
        env,
        update_mode=update_mode,
        replay_mode=replay_mode,
        training_eps=TRAINING_EPS,
        max_episode_steps=MAX_EPS_STEPS,
        epsilon_start= EPSILON_START,
        epsilon_min= EPSILON_MIN,
        decay_rate=DECAY_RATE,
        q_init=Q_INIT,
        gamma=GAMMA,
        alpha=ALPHA,
        alpha_v=ALPHA_V,
        backward_steps=BACKWARD_STEPS,
        dyna_steps=DYNA_STEPS,
        ps_steps=PS_STEPS,
        theta=THETA,
        shift_goal_ep=SHIFT_GOAL_EP,
        shift_goal_pos=SHIFT_GOAL_POS,
        add_obs_ep=ADD_OBS_EP,
        env_factory=env_factory,
        n_samples=8 # nr of samples for equally spaced replay traj plot
    )

if __name__ == "__main__":

    init_obs_count = OBSTACLES_COUNT if ADD_OBS_EP == 0 else 0

    #for UPDATE_MODE in UPDATE_MODES:
    #    for REPLAY_MODE in REPLAY_MODES:
    env, env_kwargs, initial_obstacles = make_env(UPDATE_MODE, obstacles_count=init_obs_count)
    agent = make_agent(env, UPDATE_MODE, REPLAY_MODE, initial_obstacles)
    
    agent.training()

    plot_qvalue_snapshots(
        agent,
        path=f"{OUTDIR}/heatmaps/{UPDATE_MODE}/{UPDATE_MODE}_{REPLAY_MODE}{SHIFTDIR}{OBSDIR}.png",
        grid_size=GRID_SIZE,
    )

    if REPLAY_MODE != "none":
        plot_replay_trajectories(
            agent,
            path=f"{OUTDIR}/replay_trajs/{UPDATE_MODE}/{UPDATE_MODE}_{REPLAY_MODE}{SHIFTDIR}{OBSDIR}.png",
            grid_size=GRID_SIZE,
            key_moments=True,
            only_one=True,
        )
